dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.16.5 # إصدار متوافق مع Flutter 3.29
  permission_handler: ^12.0.0+1 # إصدار ثابت ومُختبر
  device_info_plus: ^10.0.0 # بديل لـ platform_device_id
  uuid: ^4.3.3 # لتوليد UUIDs
