name: Flutter Build Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Structure
        run: |
          ls -la
          ls -la lib/
          [ -f lib/main.dart ] || exit 1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: false

      - name: Clean Workspace
        run: |
          flutter clean
          rm -rf .dart_tool
          rm -rf .packages
          rm pubspec.lock

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi
