name: Flutter Build Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Clean Workspace
        run: |
          flutter clean || true
          rm -rf .dart_tool .packages .flutter-plugins || true
          rm -f pubspec.lock || true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ble-receiver-apk
          path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk
